### ISSUE TITLE
Do not require a signal in top dead centre logs

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scippnexus#237] opened 2024-09-09 10:56 UTC
### Context

At ESS, TDC logs currently do not contain a signal. They don't technically need a signal because the logs only contain a timestamp. To accommodate this, ECDC use the special `tdct` schema instead of the usual `f144` for logs. `tdct` also does not contain extra fields such as `maximum_value` that we normally load as coordinates of a log.

~**NOTE** George is debating whether this should be changed on the ECDC side. So this issue might not need to be solved in ScippNexus.~
This won't happen in all likelihood. So if we actually need to load TDC timestamps, we need to work around the problem.

### The problem

In ScippNexus, loading a TDC log raises a warning:
```
UserWarning: Failed to load [..]/top_dead_center as NXlog: Could not determine signal field or dimensions. Falling back to loading HDF5 group children as scipp.DataGroup.
```

#### Detecting a TDC log

1. Check whether the name of the HDF5 group is `top_dead_center`,
2. or check whether the `writer_module` attr of the group is `'tdct'`,
3. or don't specialise for TDC and support loading all NXlogs without a singal.

#### Encoding the log

1. Load as a data array as normal with `da.data is da.coords['time']`. I.e., use the same variable twice.
  - The `data` is useless and may be confusing.
  - May consume extra memory if the data array is deep copied.
  - Uniform with other logs, generic code might be easier to write.
  - Can encode extra coordinates if they are added in the future.
2. Load as a variable.
  - Only the relevant data is presented.
  - No extra memory.
  - Generic code must check the type of the loaded object. Maybe not an issue because TDC logs are used differently from other logs?
  - Cannot encode extra coords if they are added in the future.

**Comment by SimonHeybrock** [comment] 2024-09-25 09:25
Duplicate of #230.

**Closed by SimonHeybrock** 2024-09-25 09:25 UTC
